### PR TITLE
1205 bcg user signs in from oauth url

### PR DESCRIPTION
**Pull request by bcgoss**
Acceptance test for viewing Access Grant page as an unauthenticated user.

### CODE REVIEW

**Comment by bcgoss** [comment]
After logging in, the page should be the the oauth_authorization_path, but is instead users_path. @j-sm-n or @PlanetEfficacy can you help me correct this?

**Comment by PlanetEfficacy** [comment]
Check the home#index... that's where devise takes the logged in user. @bcgoss

**Comment by bcgoss** [comment]
If we were hand rolling, the correct behavior would be to put `redirect_back fallback_location: root_path` in the session controller, so that the user ends up on the page they were on before they tried to log in. But Devise doesn't expose the sessions controller, unless you know how to access it. If we put `redirect_back` in home#index, it redirects to the login page instead of the page before it. (tested: "Redirected more than 5 times, check for infinite redirects.")

**Comment by bcgoss** [comment]
PR Ready for review!

**Pull request merged**
