### PR TITLE
Initial commit on sign up with email spec

### PR DESCRIPTION
**Pull request by PlanetEfficacy**

### CODE REVIEW

**Comment by PlanetEfficacy** [comment]
@calaway This is my attempt at following team workflow norms with this work in progress PR.

**Comment by bcgoss** [comment]
Crazy idea: Should we include a "Preferred Name" for people like Calaway? Maybe that's a backlog issue

**Comment by PlanetEfficacy** [comment]
Re: preferred name, I'd say the place for that is the full sign up form where we collect all the information.

**Comment by bcgoss** [comment]
Thanks for updating that name. I like this code.

**Pull request merged**
